# Generated by Django 4.0.2 on 2022-02-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login_page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=10)),
                ('mobile_no', models.IntegerField(max_length=15)),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
