# Generated by Django 4.0.2 on 2022-02-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_page',
            name='email_id',
            field=models.EmailField(max_length=50),
        ),
    ]
