# Generated by Django 4.0.2 on 2022-02-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_form', '0002_alter_login_page_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_page',
            name='mobile_no',
            field=models.CharField(max_length=15),
        ),
    ]
